# Generated by Django 4.0 on 2022-08-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BallotBox',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('initTimestamp', models.DateTimeField()),
                ('endTimestamp', models.DateTimeField()),
                ('contractAddress', models.CharField(max_length=44, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('imgPath', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=500)),
                ('website', models.URLField()),
                ('motto', models.CharField(max_length=100)),
                ('ballotParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ballotbox')),
            ],
        ),
    ]
