# Generated by Django 4.0 on 2022-08-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ballotbox_contractaddress_alter_ballotbox_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballotbox',
            old_name='contractAddress',
            new_name='contract_address',
        ),
        migrations.RenameField(
            model_name='ballotbox',
            old_name='endTimestamp',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='ballotbox',
            old_name='initTimestamp',
            new_name='start_datetime',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='ballotParent',
            new_name='ballot_parent',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='imgPath',
            new_name='img_path',
        ),
    ]
