# Generated by Django 4.0 on 2022-08-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_contractaddress_ballotbox_contract_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='id_for_ballot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
