# Generated by Django 4.0 on 2022-08-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_candidate_unique_id_for_ballot_ballot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidate',
            name='unique_id_for_ballot_ballot',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='id_for_ballot',
            new_name='pk_inside_ballot',
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('pk_inside_ballot', 'ballot_parent'), name='unique_pk_inside_ballot_ballot'),
        ),
    ]
